/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppCrudRouteRouteImport } from './routes/_app/crud/route'
import { Route as AppCrudSummaryRouteRouteImport } from './routes/_app/crud/summary/route'
import { Route as AppCrudSearchRouteRouteImport } from './routes/_app/crud/search/route'
import { Route as AppCrudDetailIdRouteRouteImport } from './routes/_app/crud/detail/$id/route'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCrudRouteRoute = AppCrudRouteRouteImport.update({
  id: '/crud',
  path: '/crud',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCrudSummaryRouteRoute = AppCrudSummaryRouteRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppCrudRouteRoute,
} as any)
const AppCrudSearchRouteRoute = AppCrudSearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppCrudRouteRoute,
} as any)
const AppCrudDetailIdRouteRoute = AppCrudDetailIdRouteRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => AppCrudRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteRouteWithChildren
  '/crud': typeof AppCrudRouteRouteWithChildren
  '/crud/search': typeof AppCrudSearchRouteRoute
  '/crud/summary': typeof AppCrudSummaryRouteRoute
  '/crud/detail/$id': typeof AppCrudDetailIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteRouteWithChildren
  '/crud': typeof AppCrudRouteRouteWithChildren
  '/crud/search': typeof AppCrudSearchRouteRoute
  '/crud/summary': typeof AppCrudSummaryRouteRoute
  '/crud/detail/$id': typeof AppCrudDetailIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/crud': typeof AppCrudRouteRouteWithChildren
  '/_app/crud/search': typeof AppCrudSearchRouteRoute
  '/_app/crud/summary': typeof AppCrudSummaryRouteRoute
  '/_app/crud/detail/$id': typeof AppCrudDetailIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crud'
    | '/crud/search'
    | '/crud/summary'
    | '/crud/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crud' | '/crud/search' | '/crud/summary' | '/crud/detail/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/crud'
    | '/_app/crud/search'
    | '/_app/crud/summary'
    | '/_app/crud/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/crud': {
      id: '/_app/crud'
      path: '/crud'
      fullPath: '/crud'
      preLoaderRoute: typeof AppCrudRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/crud/summary': {
      id: '/_app/crud/summary'
      path: '/summary'
      fullPath: '/crud/summary'
      preLoaderRoute: typeof AppCrudSummaryRouteRouteImport
      parentRoute: typeof AppCrudRouteRoute
    }
    '/_app/crud/search': {
      id: '/_app/crud/search'
      path: '/search'
      fullPath: '/crud/search'
      preLoaderRoute: typeof AppCrudSearchRouteRouteImport
      parentRoute: typeof AppCrudRouteRoute
    }
    '/_app/crud/detail/$id': {
      id: '/_app/crud/detail/$id'
      path: '/detail/$id'
      fullPath: '/crud/detail/$id'
      preLoaderRoute: typeof AppCrudDetailIdRouteRouteImport
      parentRoute: typeof AppCrudRouteRoute
    }
  }
}

interface AppCrudRouteRouteChildren {
  AppCrudSearchRouteRoute: typeof AppCrudSearchRouteRoute
  AppCrudSummaryRouteRoute: typeof AppCrudSummaryRouteRoute
  AppCrudDetailIdRouteRoute: typeof AppCrudDetailIdRouteRoute
}

const AppCrudRouteRouteChildren: AppCrudRouteRouteChildren = {
  AppCrudSearchRouteRoute: AppCrudSearchRouteRoute,
  AppCrudSummaryRouteRoute: AppCrudSummaryRouteRoute,
  AppCrudDetailIdRouteRoute: AppCrudDetailIdRouteRoute,
}

const AppCrudRouteRouteWithChildren = AppCrudRouteRoute._addFileChildren(
  AppCrudRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppCrudRouteRoute: typeof AppCrudRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCrudRouteRoute: AppCrudRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
